/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'heroicons-solid\'">' + entity + '</span>' + html;
	}
	var icons = {
		'hero-solid-adjustments': '&#xe916;',
		'hero-solid-annotation': '&#xe91c;',
		'hero-solid-archive': '&#xe970;',
		'hero-solid-arrow-circle-down': '&#xe956;',
		'hero-solid-arrow-circle-left': '&#xe92d;',
		'hero-solid-arrow-circle-right': '&#xe938;',
		'hero-solid-arrow-circle-up': '&#xe91a;',
		'hero-solid-arrow-down': '&#xe976;',
		'hero-solid-arrow-left': '&#xe908;',
		'hero-solid-arrow-narrow-down': '&#xe95b;',
		'hero-solid-arrow-narrow-left': '&#xe926;',
		'hero-solid-arrow-narrow-right': '&#xe96f;',
		'hero-solid-arrow-narrow-up': '&#xe93a;',
		'hero-solid-arrow-right': '&#xe940;',
		'hero-solid-arrow-up': '&#xe983;',
		'hero-solid-at-symbol': '&#xe97c;',
		'hero-solid-bell': '&#xe946;',
		'hero-solid-book-open': '&#xe989;',
		'hero-solid-bookmark': '&#xe979;',
		'hero-solid-briefcase': '&#xe94c;',
		'hero-solid-calendar': '&#xe97e;',
		'hero-solid-camera': '&#xe913;',
		'hero-solid-cash': '&#xe92e;',
		'hero-solid-chart-pie': '&#xe90c;',
		'hero-solid-chat': '&#xe941;',
		'hero-solid-check': '&#xe91b;',
		'hero-solid-check-circle': '&#xe986;',
		'hero-solid-cheveron-down': '&#xe90d;',
		'hero-solid-cheveron-left': '&#xe971;',
		'hero-solid-cheveron-right': '&#xe985;',
		'hero-solid-cheveron-up': '&#xe928;',
		'hero-solid-clipboard': '&#xe982;',
		'hero-solid-clipboard-check': '&#xe987;',
		'hero-solid-clipboard-copy': '&#xe911;',
		'hero-solid-clipboard-list': '&#xe958;',
		'hero-solid-clock': '&#xe959;',
		'hero-solid-cloud-download': '&#xe901;',
		'hero-solid-cloud-upload': '&#xe91f;',
		'hero-solid-code': '&#xe94e;',
		'hero-solid-cog': '&#xe90e;',
		'hero-solid-collection': '&#xe93c;',
		'hero-solid-color-swatch': '&#xe94d;',
		'hero-solid-credit-card': '&#xe94a;',
		'hero-solid-currency-dollar': '&#xe97f;',
		'hero-solid-currency-euro': '&#xe91d;',
		'hero-solid-currency-pound': '&#xe988;',
		'hero-solid-currency-rupee': '&#xe96a;',
		'hero-solid-currency-yen': '&#xe980;',
		'hero-solid-document': '&#xe929;',
		'hero-solid-document-add': '&#xe923;',
		'hero-solid-document-download': '&#xe948;',
		'hero-solid-document-duplicate': '&#xe978;',
		'hero-solid-document-remove': '&#xe97b;',
		'hero-solid-dots-circle-horizontal': '&#xe919;',
		'hero-solid-dots-horizontal': '&#xe906;',
		'hero-solid-dots-vertical': '&#xe939;',
		'hero-solid-download': '&#xe937;',
		'hero-solid-duplicate': '&#xe954;',
		'hero-solid-emoji-happy': '&#xe931;',
		'hero-solid-emoji-sad': '&#xe902;',
		'hero-solid-exclamation': '&#xe973;',
		'hero-solid-exclamation-circle': '&#xe968;',
		'hero-solid-external-link': '&#xe933;',
		'hero-solid-eye': '&#xe974;',
		'hero-solid-filter': '&#xe930;',
		'hero-solid-flag': '&#xe94f;',
		'hero-solid-folder': '&#xe93f;',
		'hero-solid-globe': '&#xe943;',
		'hero-solid-globe-alt': '&#xe96b;',
		'hero-solid-hashtag': '&#xe921;',
		'hero-solid-heart': '&#xe95e;',
		'hero-solid-home': '&#xe98a;',
		'hero-solid-inbox': '&#xe93b;',
		'hero-solid-inbox-in': '&#xe934;',
		'hero-solid-information-circle': '&#xe963;',
		'hero-solid-light-bulb': '&#xe915;',
		'hero-solid-lightning-bolt': '&#xe92f;',
		'hero-solid-link': '&#xe964;',
		'hero-solid-location-marker': '&#xe935;',
		'hero-solid-lock-closed': '&#xe981;',
		'hero-solid-lock-open': '&#xe92b;',
		'hero-solid-mail': '&#xe967;',
		'hero-solid-mail-open': '&#xe90b;',
		'hero-solid-menu': '&#xe905;',
		'hero-solid-menu-alt-1': '&#xe966;',
		'hero-solid-menu-alt-2': '&#xe95c;',
		'hero-solid-menu-alt-3': '&#xe961;',
		'hero-solid-menu-alt-4': '&#xe947;',
		'hero-solid-minus-circle': '&#xe95d;',
		'hero-solid-moon': '&#xe914;',
		'hero-solid-office-building': '&#xe96e;',
		'hero-solid-paper-clip': '&#xe942;',
		'hero-solid-pencil': '&#xe920;',
		'hero-solid-pencil-alt': '&#xe92c;',
		'hero-solid-phone': '&#xe95a;',
		'hero-solid-phone-incoming': '&#xe922;',
		'hero-solid-phone-outgoing': '&#xe96d;',
		'hero-solid-photograph': '&#xe900;',
		'hero-solid-plus': '&#xe953;',
		'hero-solid-plus-circle': '&#xe952;',
		'hero-solid-printer': '&#xe909;',
		'hero-solid-qrcode': '&#xe977;',
		'hero-solid-question-mark-circle': '&#xe94b;',
		'hero-solid-receipt-refund': '&#xe932;',
		'hero-solid-refresh': '&#xe912;',
		'hero-solid-reply': '&#xe92a;',
		'hero-solid-scale': '&#xe917;',
		'hero-solid-search': '&#xe944;',
		'hero-solid-selector': '&#xe93e;',
		'hero-solid-share': '&#xe957;',
		'hero-solid-shield-check': '&#xe951;',
		'hero-solid-shield-exclamation': '&#xe945;',
		'hero-solid-sort-ascending': '&#xe904;',
		'hero-solid-sort-descending': '&#xe90a;',
		'hero-solid-sparkles': '&#xe903;',
		'hero-solid-sun': '&#xe969;',
		'hero-solid-switch-horizontal': '&#xe950;',
		'hero-solid-switch-vertical': '&#xe97d;',
		'hero-solid-tag': '&#xe91e;',
		'hero-solid-template': '&#xe955;',
		'hero-solid-ticket': '&#xe95f;',
		'hero-solid-translate': '&#xe965;',
		'hero-solid-trash': '&#xe984;',
		'hero-solid-trending-down': '&#xe93d;',
		'hero-solid-trending-up': '&#xe972;',
		'hero-solid-upload': '&#xe936;',
		'hero-solid-user': '&#xe98b;',
		'hero-solid-user-add': '&#xe925;',
		'hero-solid-user-circle': '&#xe949;',
		'hero-solid-user-group': '&#xe910;',
		'hero-solid-user-remove': '&#xe927;',
		'hero-solid-users': '&#xe962;',
		'hero-solid-view-boards': '&#xe924;',
		'hero-solid-view-list': '&#xe96c;',
		'hero-solid-volume-off': '&#xe975;',
		'hero-solid-volume-up': '&#xe907;',
		'hero-solid-x': '&#xe97a;',
		'hero-solid-x-circle': '&#xe918;',
		'hero-solid-zoom-in': '&#xe90f;',
		'hero-solid-zoom-out': '&#xe960;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/hero-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
